CREATE USER UNIVERSITY_SCHEDULE_ADMIN identified by 0
DEFAULT TABLESPACE UNIVERSITY_SCHEDULE_TABLESPACE
QUOTA UNLIMITED ON UNIVERSITY_SCHEDULE_TABLESPACE;

GRANT CREATE SESSION, GRANT ANY PRIVILEGES TO UNIVERSITY_SCHEDULE_ADMIN;
