CREATE SEQUENCE UNIVERSITY_SCHEDULE_ADMIN.GRADE_SEQUENCE
START WITH 1
INCREMENT BY 1
NOMAXVALUE;

CREATE SEQUENCE UNIVERSITY_SCHEDULE_ADMIN.LECTURER_SEQUENCE
START WITH 1
INCREMENT BY 1
NOMAXVALUE;

CREATE SEQUENCE UNIVERSITY_SCHEDULE_ADMIN.UNIVERSITY_BUILDING_SEQUENCE
START WITH 1
INCREMENT BY 1
NOMAXVALUE;

CREATE SEQUENCE UNIVERSITY_SCHEDULE_ADMIN.LECTURE_HALL_SEQUENCE
START WITH 1
INCREMENT BY 1
NOMAXVALUE;

CREATE SEQUENCE UNIVERSITY_SCHEDULE_ADMIN.GROUPS_SEQUENCE
START WITH 1
INCREMENT BY 1
NOMAXVALUE;

CREATE SEQUENCE UNIVERSITY_SCHEDULE_ADMIN.LISTENER_SEQUENCE
START WITH 1
INCREMENT BY 1
NOMAXVALUE;

CREATE SEQUENCE UNIVERSITY_SCHEDULE_ADMIN.STUDY_GROUPS_SEQUENCE
START WITH 1
INCREMENT BY 1
NOMAXVALUE;

CREATE SEQUENCE UNIVERSITY_SCHEDULE_ADMIN.CLASSES_FORM_SEQUENCE
START WITH 1
INCREMENT BY 1
NOMAXVALUE;

CREATE SEQUENCE UNIVERSITY_SCHEDULE_ADMIN.SCHEDULE_SEQUENCE
START WITH 1
INCREMENT BY 1
NOMAXVALUE;

